#
# (C) Copyright 2017 Emerson
# (C) Copyright 2017 Rodolfo Giometti <giometti@enneenne.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= ipro4.o
obj-$(CONFIG_AT91_LED) += led.o
obj-$(CONFIG_HAS_DATAFLASH) += partition.o
